package com.adappvark.toolkit

/**
 * Build configuration constants
 * These will be auto-generated by Gradle in production
 */
object BuildConfig {
    const val APPLICATION_ID = "com.adappvark.toolkit"
    const val VERSION_NAME = "1.0.0"
    const val VERSION_CODE = 1
    const val DEBUG = true
    
    // Build type
    const val BUILD_TYPE = "debug"
}
