package com.adappvark.toolkit

/**
 * Build configuration constants.
 *
 * Note: Ideally this would be auto-generated by Gradle with `buildFeatures { buildConfig = true }`,
 * but JDK 21 + Android SDK 35 has a jlink transform bug that prevents Java compilation.
 * This manual file is used as a workaround.
 *
 * IMPORTANT: Keep these values in sync with app/build.gradle.kts defaultConfig.
 * DEBUG must be false for release/dApp Store builds.
 */
object BuildConfig {
    const val APPLICATION_ID = "com.adappvark.toolkit"
    const val VERSION_NAME = "1.0.5"
    const val VERSION_CODE = 6

    // Production: false. Debug logging, payment bypass, and dev tools are disabled.
    const val DEBUG = false

    // Build type
    const val BUILD_TYPE = "release"
}
